CREATE TABLE BATCH_JOB_INSTANCE  (
    JOB_INSTANCE_ID BIGINT  NOT NULL PRIMARY KEY ,
    VERSION BIGINT ,
    JOB_NAME VARCHAR(100) NOT NULL,
    JOB_KEY VARCHAR(32) NOT NULL,
    constraint JOB_INST_UN unique (JOB_NAME, JOB_KEY)
) ;

CREATE TABLE BATCH_JOB_EXECUTION  (
    JOB_EXECUTION_ID BIGINT  NOT NULL PRIMARY KEY ,
    VERSION BIGINT  ,
    JOB_INSTANCE_ID BIGINT NOT NULL,
    CREATE_TIME TIMESTAMP NOT NULL,
    START_TIME TIMESTAMP DEFAULT NULL ,
    END_TIME TIMESTAMP DEFAULT NULL ,
    STATUS VARCHAR(10) ,
    EXIT_CODE VARCHAR(2500) ,
    EXIT_MESSAGE VARCHAR(2500) ,
    LAST_UPDATED TIMESTAMP,
    JOB_CONFIGURATION_LOCATION VARCHAR(2500) NULL,
    constraint JOB_INST_EXEC_FK foreign key (JOB_INSTANCE_ID)
    references BATCH_JOB_INSTANCE(JOB_INSTANCE_ID)
) ;

CREATE TABLE BATCH_JOB_EXECUTION_PARAMS  (
    JOB_EXECUTION_ID BIGINT NOT NULL ,
    TYPE_CD VARCHAR(6) NOT NULL ,
    KEY_NAME VARCHAR(100) NOT NULL ,
    STRING_VAL VARCHAR(250) ,
    DATE_VAL TIMESTAMP DEFAULT NULL ,
    LONG_VAL BIGINT ,
    DOUBLE_VAL DOUBLE PRECISION ,
    IDENTIFYING CHAR(1) NOT NULL ,
    constraint JOB_EXEC_PARAMS_FK foreign key (JOB_EXECUTION_ID)
    references BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ;

CREATE TABLE BATCH_STEP_EXECUTION  (
    STEP_EXECUTION_ID BIGINT  NOT NULL PRIMARY KEY ,
    VERSION BIGINT NOT NULL,
    STEP_NAME VARCHAR(100) NOT NULL,
    JOB_EXECUTION_ID BIGINT NOT NULL,
    START_TIME TIMESTAMP NOT NULL ,
    END_TIME TIMESTAMP DEFAULT NULL ,
    STATUS VARCHAR(10) ,
    COMMIT_COUNT BIGINT ,
    READ_COUNT BIGINT ,
    FILTER_COUNT BIGINT ,
    WRITE_COUNT BIGINT ,
    READ_SKIP_COUNT BIGINT ,
    WRITE_SKIP_COUNT BIGINT ,
    PROCESS_SKIP_COUNT BIGINT ,
    ROLLBACK_COUNT BIGINT ,
    EXIT_CODE VARCHAR(2500) ,
    EXIT_MESSAGE VARCHAR(2500) ,
    LAST_UPDATED TIMESTAMP,
    constraint JOB_EXEC_STEP_FK foreign key (JOB_EXECUTION_ID)
    references BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ;

CREATE TABLE BATCH_STEP_EXECUTION_CONTEXT  (
    STEP_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
    SHORT_CONTEXT VARCHAR(2500) NOT NULL,
    SERIALIZED_CONTEXT TEXT ,
    constraint STEP_EXEC_CTX_FK foreign key (STEP_EXECUTION_ID)
    references BATCH_STEP_EXECUTION(STEP_EXECUTION_ID)
) ;

CREATE TABLE BATCH_JOB_EXECUTION_CONTEXT  (
    JOB_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
    SHORT_CONTEXT VARCHAR(2500) NOT NULL,
    SERIALIZED_CONTEXT TEXT ,
    constraint JOB_EXEC_CTX_FK foreign key (JOB_EXECUTION_ID)
    references BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ;

CREATE SEQUENCE BATCH_STEP_EXECUTION_SEQ MAXVALUE 9223372036854775807 NO CYCLE;
CREATE SEQUENCE BATCH_JOB_EXECUTION_SEQ MAXVALUE 9223372036854775807 NO CYCLE;
CREATE SEQUENCE BATCH_JOB_SEQ MAXVALUE 9223372036854775807 NO CYCLE;


CREATE TABLE M_LOCAL_MNG (
  NAME_JA CHARACTER VARYING(20) NOT NULL
  , LOCAL_ID CHARACTER VARYING(1) NOT NULL
  , LOCAL_NAME CHARACTER VARYING(20) NOT NULL
  , PRIMARY KEY (NAME_JA)
);

CREATE TABLE T_API_FREE_DATA (
  ID NUMERIC(2) NOT NULL
  , NAME_JA CHARACTER VARYING(20) NOT NULL
  , NAME_EN CHARACTER VARYING(20) NOT NULL
  , LAT NUMERIC(10) NOT NULL
  , LNG NUMERIC(10) NOT NULL
  , POPULATION NUMERIC(10) NOT NULL
  , CASES_DATE DATE NOT NULL
  , DEATHS_DATE DATE NOT NULL
  , PCR_DATE DATE NOT NULL
  , HOSPITALIZE_DATE DATE NOT NULL
  , SEVERE_DATE DATE NOT NULL
  , DISCHARGE_DATE DATE NOT NULL
  , SYMPTOM_CONFIRMING_DATE DATE NOT NULL
  , CASES NUMERIC(10) NOT NULL
  , DEATHS NUMERIC(10) NOT NULL
  , PCR NUMERIC(10) NOT NULL
  , HOSPITALIZE NUMERIC(10) NOT NULL
  , SEVERE NUMERIC(10) NOT NULL
  , DISCHARGE NUMERIC(10) NOT NULL
  , SYMPTOM_CONFIRMING NUMERIC(10) NOT NULL
  , PRIMARY KEY (ID)
);

CREATE TABLE T_API_SICKBED_DATA (
  ID NUMERIC(2) NOT NULL
  , NAME_JA CHARACTER VARYING(20) NOT NULL
  , ACCEPT_HOSPITALBED NUMERIC(10) NOT NULL
  , HOSPITALBED_USE_RATE NUMERIC(3) NOT NULL
  , ACCEPT_INN NUMERIC(10) NOT NULL
  , ACCEPT_INN_USE_RATE NUMERIC(3) NOT NULL
  , UPDATEDATE DATE NOT NULL
  , PRIMARY KEY (ID)
);